### ISSUE TITLE
migrate from TSD to Typings

### ISSUE THREAD

**Issue by codecorsair** [csegames/cu-ui#4]
TSD is deprecated, we need to migrate to using Typings.  https://github.com/typings/typings

**Comment by michielrutting** [comment]
Heya. I've just set up my environment here and thought I'd try Visual Studio Code instead of the full blown VS experience. Everything went pretty well, except for the fact that the editor couldn't find the imports for react and camelot-unchained in the tsx files until I ran "npm run typings" in the module directories that needed them. I don't know if other IDEs require this as well.

For convenience I modified build.js with a -t (typings) argument that installs the typings if typings.json is present and added "build:typings" in package.json, although it could be added to "build:install" as well. I could try to send a pull request if you want, but that would depend if this would actually be useful in other IDEs :)

**Comment by codecorsair** [comment]
the build process install typings, but if you want to run typings install on all sub-modules before build so that vscode is happy, then ya that would be good to add to build.js.

If you could submit that on a pull request that would be awesome!

Closing this issue as we're now using Typings.
